name: Build and Release (Windows)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  create:
    # Any branch or tag

jobs:
  build:
    name: Build for Windows (x64)
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Fetch latest evo-luvi version tag
        # This seems like a hacky way of getting the tag, but I haven't found a better one that "just works"
        run: curl --location --silent --head --output curl.log -w %{url_effective} https://github.com/evo-lua/evo-luvi/releases/latest | grep --only-matching tag/.* | cut -f2- -d/ | tee LATEST_EVO_LUVI_VERSION && cat curl.log # Print everything, for easier debugging
        shell: bash

      - name: Download evo-luvi release
        run: curl --location --silent --fail --output evo-luvi.exe https://github.com/evo-lua/evo-luvi/releases/download/$(cat LATEST_EVO_LUVI_VERSION)/evo-luvi.exe &&  ls && ./evo-luvi.exe -v # Output version to allow troubleshooting issues more easily if it's wrong
        shell: bash

      - name: Clean up temporary files # We don't want to bloat the bundle with these
        run: rm -v LATEST_EVO_LUVI_VERSION curl.log && mv evo-luvi.exe .. # We still need the runtime, but not in cwd
        shell: bash

      - name: Make executable
        # Modifiy path so we can use evo-luvi from the parent dir (avoids it getting added to the bundle twice)
        run: cd .. && dir && evo-luvi evo -o evo/evo.exe && dir && dir evo
        shell: cmd

      # We don't want to deploy a faulty release
      - name: Verify the build
        run: test.cmd
        shell: cmd

      - name: Publish new release
        # Truly "continuous" releases may be overkill here, so better only release tagged versions
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: evo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}